### ISSUE TITLE
Which perl on windows?

### ISSUE THREAD

**Issue by lucvdv** [raix/vscode-perl-debug#1] opened 2016-11-25 14:41 UTC
What version of Perl are you using?

I'm not a VS Code expert by far, but so far, I got this plug-in to work only with cygwin perl (I'm running Windows 10, BTW, and my cygwin is the 64 bit variety).
Even there it will step through code, but it won't let me examine variables.
Did I misunderstand that variables don't work in mouse hover mode, but should appear in the 'variables' and 'watch' panes? The variables pane just remains empty, and adding anything in the watch pane doesn't give the expected result.

With ActiveState Community Perl 32 bit, it looks like the perl.exe executable is started, but no output from it ever reaches the debugger. I tried ActiveState 64 bit with the same visible result (i.e. nothing), but I didn't check if perl.exe was launched in that case.
Both versions *did* work fine at a command prompt though.

With Strawberry Perl 64 bit, some output reached the debugger, but it was all error messages about not being able to determine the console window size and such, and it never reached the first breakpoint in the Perl code I was debugging (just a small test, barely above "hello world" functionality).

Does anyone have an idea of anything that might be tried to get around these problems?

**Comment by raix** [comment] 2016-11-25 23:11
Hi @lucvdv I'm on linux and mac os using perl 5 (I'm guessing 64bit) and it works fine - I'm thinking there might be a difference in the windows version - but I'm not sure, I'll have to test

This weekend I'll be adding the rest of the stepping functions, variable setting, variables on hover (partial), watch and perhaps function breakpoints.

I have to test how things work on perl 6 (which is really a different language - I might have to scope this debugger for v5)

I'm not sure about the terminal size errors - I have to investigate

**Comment by raix** [comment] 2016-11-27 21:35
I've published v0.1.1 - added:
* watch variables and expressions
* set variables from inspector
* step in
* step out
* hover tries to get values (might not work in hash children)

I'm not 100% sure but the adapter connects to the perl debugger via 3 streams STDIN/STDOUT/STDERR

Potential issues to investigate:
* it could be a newline thing LF vs CRLF etc. (I have been stripping \r chars always though)
* For the window size thing - not sure - but I might have to wrap the perl debugger somehow

**Comment by raix** [comment] 2016-11-28 21:29
@lucvdv can you give 0.1.2 a go?
I've enabled `shell` meaning it should now run in a command line shell environment - it might solve the terminal size issue.

**Comment by lucvdv** [comment] 2016-11-29 13:53
Hi @raix, sorry for the delay, but I'm rather busy this week.

It looks like shell isn't the solution, now a console window pops up in which 'perl -d' is started and can be seen waiting for input, but it looks like its stdout just ends up on screen and isn't received by VS Code.

Console window contents:

    Loading DB routines from perl5db.pl version 1.49
    Editor support available.
    
    Enter h or 'h h' for help, or 'man perldebug' for more help.
    
    main::(filter.pl:5):    my $x = 0;
      DB<1>

This is using the cygwin perl that first gave the best results. It may be somewhat behind with updates, but not very far. It's 5.22.2, I don't know exactly what is current today.

**Comment by raix** [comment] 2016-12-03 19:44
@lucvdv I've setup a CI test matrix between OSX / Linux / Windows and multiple versions of perl.

Windows versions of perl are not 100% consistent with those of mac/linux - There are currently two issues, variable inspection is the worst (haven't had time to test it in Activeperl - might be stable)

for now I've added Strawberry perl and active perl - cygwin might be next.

I've also found a workaround the terminal window size thing - and turned off the output.

I haven't had the chance to actually tryout code on windows (so I'd be thrilled if you could give it a go)

**Comment by biocomp** [comment] 2016-12-07 00:48
+1 for the issue, now with Citrus perl. I understand that you're not testing with every possible perl/OS combination, but maybe that's something that is easy to solve?

I'm also getting the initial output:
```
E:/bin/perl/bin/perl.exe -d slic3r.pl
Loading DB routines from perl5db.pl version 1.37
Editor support available.
Enter h or 'h h' for help, or 'perldoc perldebug' for more help.
main::(slic3r.pl:17):	$|++;
```

Then script continues to run w/o stopping, and debugger seems to be detached: If I try to do anything with debug console, I get this:

```
h
Please start a debug session to evaluate
```

**Comment by biocomp** [comment] 2016-12-07 06:21
Does not work with ActivePerl on Windows either. Simple hello world file, won't hit breakpoints, will start debugging, but won't really debug anything - debug session stops right away.

**Comment by lucvdv** [comment] 2016-12-07 07:47
I won't have much time to help debugging for the next month or so, and new projects will probably start popping up and interfering after that. But I think the problem is that all Windows versions of Perl have to compensate for the \r\n line ends in some way, and no two of them do it in the same way or to the same degree.
I've tried cygwin (which seems to give the best results), Strawberry and ActivePerl, but what I haven't tried yet, is Perl in the new 'Ubuntu on Windows' subsystem that Microsoft and Canonical created together for Windows 10.

UoW just might give the best result of all, *if* you can find a way to start the Ubunutu binaries from a windows process. But that just might be the problem here...
When I examine them in task manager, I see that there's a "microsoft bash launcher" (bash.exe) sitting between Windows and the Ubuntu binaries. That's logical, something has to provide the subsystem, the linux kernel those binaries think they're running under, just like there used to be a now-abandoned posix subsystem besides the win32 subsystem in older versions of Windows in the NT line.
When you "open file location" on that bash.exe in task manager it takes you to the Windows\system32 directory, but when you try the same on the actual bash or perl binary that is running in the Ubuntu subsystem, it doesn't take you anywhere at all, it doesn't open anything.

The files can be found as explained here: [http://askubuntu.com/questions/759880/where-is-the-ubuntu-file-system-root-directory-in-windows-nt-subsystem-and-vice](http://askubuntu.com/questions/759880/where-is-the-ubuntu-file-system-root-directory-in-windows-nt-subsystem-and-vice.)
The Lxss directory becomes visible only when you unhide 'protected operating system files'.
Because the applications installed there are the same binaries you find on a real Ubuntu system, you can't just launch them on Windows.

**Comment by lucvdv** [comment] 2016-12-07 07:58
Just another thing: I noticed when trying to SSH into Linux systems from a Windows .Net application some time ago, that stdin and stdout didn't work as I expected at all. They behaved completely LINE oriented, not character oriented.

I tried with Putty (plink) and with another SSH client, with the same result.
In both cases, trying to wait for a command prompt at the remote side never worked, because my application would receive that prompt only *after* the remote site had also outputted a newline.

It could have been the .Net framework that was to blame there, but I hope it's not the same thing that makes the debug console look like it does nothing in some cases here.

**Comment by lucvdv** [comment] 2016-12-07 08:34
I couldn't resist and put some more time in it than I had ;)
Found that running Ubuntu perl under Windows won't be that hard after all. Just use it through the bash.exe that Ubuntu on Windows installs in system32.

    C:\Users\lucvdv>C:\Windows\System32\bash.exe -c 'perl --version'
    
    This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
    (with 44 registered patches, see perl -V for more detail)
    
    Copyright 1987-2013, Larry Wall
    
    Perl may be copied only under the terms of either the Artistic License or the
    GNU General Public License, which may be found in the Perl 5 source kit.
    
    Complete documentation for Perl, including FAQ lists, should be found on
    this system using "man perl" or "perldoc perl".  If you have access to the
    Internet, point your browser at http://www.perl.org/, the Perl Home Page.
    
    
    C:\Users\lucvdv>C:\cygwin\bin\bash.exe -c 'perl --version'
    
    This is perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x64-multi-thread
    
    Copyright 1987-2016, Larry Wall
    
    Perl may be copied only under the terms of either the Artistic License or the
    GNU General Public License, which may be found in the Perl 5 source kit.
    
    Complete documentation for Perl, including FAQ lists, should be found on
    this system using "man perl" or "perldoc perl".  If you have access to the
    Internet, point your browser at http://www.perl.org/, the Perl Home Page.

This also shows that Ubuntu on Windows is lagging behind cygwin on perl version level.
Even my Raspberry Pi's Raspbian is more recent, perl 5.20.2.
On Ubuntu 12.04 LTS it is 5.14.2, that's the most recent 'real' Ubuntu I have around.

**Comment by raix** [comment] 2016-12-07 18:21
great work @lucvdv maybe we should create a wiki or howto with your experience - I'm not sure if it can solve anything but theres an option `exec` that defaults to `perl` - you might be able to set the executable to the perl version you want? (maybe you can try setting exec in launch.json to `C:\cygwin\bin\bash.exe -c perl` and see if that could work)

Otherwise we need a way to set the environment eg. bash/cygwin etc.?

https://github.com/raix/vscode-perl-debug/blob/master/src/extension.ts#L11

**Comment by raix** [comment] 2016-12-07 18:27
@biocomp I would like to add more perl distributions so cygwin, citrus.

I'm not sure why Active perl isn't working - it's running in the test matrix - Can I get you to clone the repo and run `npm install` then `npm test` to see if tests are failing? *(if they are then we need to find the installation differences - if not then we need more test coverage)*

**Comment by biocomp** [comment] 2016-12-08 01:22
@raix `npm install` gave me this (looks like other dependencies were ok):

```
npm http GET https://registry.npmjs.org/vscode-debugadapter
npm http GET https://registry.npmjs.org/vscode
npm http GET https://registry.npmjs.org/vscode-debugadapter-testsupport
npm http GET https://registry.npmjs.org/vscode-debugprotocol
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/vscode-debugprotocol
npm http 304 https://registry.npmjs.org/vscode-debugadapter-testsupport
npm http 304 https://registry.npmjs.org/vscode
npm http 304 https://registry.npmjs.org/vscode-debugadapter
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/types/es6-promise
npm http GET https://registry.npmjs.org/types/mocha
npm http GET https://registry.npmjs.org/types/node
npm http 404 https://registry.npmjs.org/types/es6-promise
npm http 404 https://registry.npmjs.org/types/node
npm http 404 https://registry.npmjs.org/types/mocha
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'perl-debug'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\ProgramData\\Chocolatey\\lib\\nodejs.commandline\\tools\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd E:\Win8Users\UserName\Source\Repos\PerlInVsCode\vscode-perl-debug
npm ERR! node -v v5.10.1
npm ERR! npm -v 1.4.9
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\Win8Users\UserName\Source\Repos\PerlInVsCode\vscode-perl-debug\npm-debug.log
npm ERR! not ok code 0
```

**Comment by biocomp** [comment] 2016-12-08 19:58
Ok, it was a silly mistake on my side - npm was not set up correctly.

Here's npm test output attached [NpmTestOutput.txt](https://github.com/raix/vscode-perl-debug/files/640440/NpmTestOutput.txt)

Basically, most tests failed with:
`Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
`

**Comment by raix** [comment] 2016-12-08 22:51
@biocomp thanks for taking the time
I need some specs on perl/windows/terminal versions - Ideally we should be able to replicate on ci

It sounds like the perl debugger doesn't end requests like normal perl debuggers or theres a terminal issue.

**Comment by biocomp** [comment] 2016-12-11 19:09
Ok, ok. So, I had incomplete perl installation. So now, with both citrus perl and active perl, `npm test` almost completely succeeded, giving me these errors:

```
 26 passing (8s)
  1 failing

  1) Perl debugger connection Test debugger getVariableList Should get more scope variables types:
     Error: PadWalker module not found - please install
      at perlDebuggerConnection.<anonymous> (out\adapter.js:393:23)
      at Generator.next (<anonymous>)
      at fulfilled (out\adapter.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

After I installed PadWalker into both "perls", the tests passed! The only thing is that I get one cmd window pop up with some perl program (C:\Perl64\bin\perl.exe -d -I C:/Perl64/site/lib -I C:/Perl64/lib -I . test.pl )under debugger:

```
Loading DB routines from perl5db.pl version 1.49_04
Editor support available.

Enter h or 'h h' for help, or 'perldoc perldebug' for more help.

main::(test.pl:5):      print "Testing\n";
  DB<0>
```

The problem is though... that **still trying to debug something through vscode doesn't work**. It works with ActivePerl on one of my boxes, but doesn't work on another one. The process starts, but debugger seems to be loosing connection after printing out the first line.

So the versions of tools on non-working box:
Windows: 
Windows 10, x64 Version 1607, osbuild 14393.479

Perl: 
This is perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)
Binary build 2400 [300558] provided by ActiveState http://www.ActiveState.com
Built Jun  9 2016 21:44:59

Cmd.exe: 10.0.14393.0

**Comment by raix** [comment] 2016-12-11 19:25
Thank you for the detective work, @biocomp Ill look into it

**Comment by raix** [comment] 2017-05-23 14:53
I'm closing this issue, tracking perl distributions in #9 - and working on adding more "adapter" tests - these are closer to an e2e test than the connection tests. There are still a couple of adapter tests skipped / wip.
I've added more versions of Strawberry perl distributions we should do the same with activeperl etc. to get a full test matrix.

Please let me know if we need to break down into more issues.

**Closed by raix** 2017-05-23 14:53 UTC
