### ISSUE TITLE
Path resolution for stepping into gives wrong paths.

### ISSUE THREAD

**Issue by DonRomanos** [raix/vscode-perl-debug#18] opened 2017-03-13 09:49 UTC
If i want to step into a method not in the currently used module, the debugger tries to resolve the path to the required module. However it always prepends the path of the current working directory to the module which the results in something like:

e:\C:\Strawberry\perl\lib\perl5db.pl which is obviously wrong. 

The working directory here is just e:\\ . If i change the working directory to e:\\Temp then it prepends:

e:\temp\C:\Strawberry\perl\lib\perl5db.pl

This issue is probably related to the 'can't find 'perl5db.pl' issue as in one of the comments the same path resolution was described.

**Comment by raix** [comment] 2017-03-14 16:57
Seems related / duplicate of #16 #3 
It's top priority to implement a proper file resolver *(eg. perl knows best..)* [board](https://github.com/raix/vscode-perl-debug/projects/1)

**Comment by raix** [comment] 2017-03-24 21:58
should be fixed, released in [0.2.0](https://github.com/raix/vscode-perl-debug/releases/tag/v0.2.0) - please reopen if the issue persists

**Closed by raix** 2017-03-24 21:58 UTC
